name: Build application
on:
  pull_request:
jobs:
  build:
    runs-on: windows-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
    
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
            host: 'windows'
            target: 'desktop'
      - name: Build
        run: |
          ls
          qmake jxl-batch-converter.pro CONFIG+=qtquickcompiler
          export QT_MSVC_VERSION=2019
          make
      - run: ls
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
           name: build
           path: ./build